# Generated by Django 3.2.16 on 2025-08-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
